# .golangci.yml
version: 2

run:
  timeout: 5m
  modules-download-mode: readonly
  exclude-dirs:
    - examples
  exclude-dirs-use-default: false

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - unused
    - gocritic
    - bodyclose
    - goconst
    - gocyclo
    - misspell
    - prealloc
    - whitespace

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/hussainpithawala/state-machine-amz-go
  gocritic:
    enabled-tags:
      - performance
      - style
      - diagnostic
    disabled-checks:
      - hugeParam

issues:
  exclude-dirs:
    - examples
    - ./examples
    - examples/
    - examples/**
    - ./examples/**
  exclude-files:
    - ".*_test\\.go"
  exclude-rules:
    - path: examples/
      linters:
        - revive
        - misspell
        - unused
        - gocyclo
        - goconst
        - errcheck
  max-same-issues: 50
  max-issues-per-linter: 50